repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: ^(docs/|patch/)
      - id: trailing-whitespace
      - id: check-shebang-scripts-are-executable

  - repo: local
    hooks:
      - id: pre-commit-autoupdate
        name: Update pre-commit hooks
        entry: pwsh -c "pre-commit autoupdate; git add .pre-commit-config.yaml"
        language: system
        pass_filenames: false

  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.16.1
    hooks:
      - id: zizmor
