name: ci - workflow-vs-current-builds

on:
  workflow_call:
    inputs:
      force_build:
        type: string
        required: false
    outputs:
      build-qbittorrent-nox:
        value: ${{ jobs.workflow-vs-current-builds.outputs.build-qbittorrent-nox }}

jobs:
  workflow-vs-current-builds:
    runs-on: ubuntu-24.04
    outputs:
      build-qbittorrent-nox: ${{ steps.build-qbittorrent-nox.outputs.build-qbittorrent-nox }}
    env:
      force_build: ${{ inputs.force_build }}
    steps:
      - name: re-bootstrap updated current_workflow_version array values to file
        run: |
          until curl -sLf "https://github.com/userdocs/qbt-workflow-files/releases/latest/download/dependency-version.json" > current_workflow_version.json; do
              echo "waiting for URL."
              sleep 2
          done
          echo 'declare -A current_workflow_version' > current_workflow_version.sh
          jq -r 'to_entries[]|@sh"current_workflow_version[\(.key)]=\(.value)"' current_workflow_version.json >> current_workflow_version.sh

      - name: bootstrap current_build_version array values to file
        run: |
          until curl -sLf "https://github.com/userdocs/qbittorrent-nox-static/releases/latest/download/dependency-version.json" > current_build_version.json; do
              echo "waiting for URL."
              sleep 2
          done
          echo 'declare -A current_build_version' > current_build_version.sh
          jq -r 'to_entries[]|@sh"current_build_version[\(.key)]=\(.value)"' < <(jq 'del(.revision)' current_build_version.json) >> current_build_version.sh

      - name: Test values - workflow files vs current build
        id: build-qbittorrent-nox
        run: |
          source current_workflow_version.sh
          source current_build_version.sh

          ver() {
            local test_array
            read -ra test_array < <(printf "%s" "${@//./ }")
            printf "%d%03d%03d%03d" "${test_array[@]}"
          }

          for iray in "${!current_build_version[@]}"; do
            if [[ "$(ver "${current_workflow_version[$iray]}")" -gt "$(ver "${current_build_version[$iray]}")" ]]; then
              printf "%-14s qbt-workflow-files:%-10s qbt-static-current:%-10s %s\n" "$iray" "${current_workflow_version[$iray]}" "${current_build_version[$iray]}" "< New version available - workflow will be triggered"
              printf '%s\n' "build-qbittorrent-nox=true" >> $GITHUB_OUTPUT
            else
              printf "%-14s qbt-workflow-files:%-10s qbt-static-current:%-10s\n" "$iray" "${current_workflow_version[$iray]}" "${current_build_version[$iray]}"
            fi
          done

          if [[ "${force_build}" == 'true' ]]; then
            printf '%s\n' "build-qbittorrent-nox=true" >> $GITHUB_OUTPUT
          fi
